language: objective-c
osx_image: xcode7.2
script:
- set -o pipefail && xcodebuild test -project StringFilter.xcodeproj -scheme StringFilter -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" ONLY_ACTIVE_ARCH=NO | xcpretty

